marks= []

f1 = input("Enter the name of first marks here: ")
marks.append(f1)   
f2 = input("Enter the name of second marks here : ")
marks.append(f2)                                               
f3 = input("Enter the name of third marks here:")
marks.append(f3)   
f4 = input("Enter the name of fourth marks here: ")
marks.append(f4)   
f5 = input("Enter the name of fifth marks here: ")
marks.append(f5)
f6 = input("Enter the name of sixth marks here: ")
marks.append(f6) 
marks.sort()           
print(marks)      